name: "Linting"

on:
  push:
    branches: [main]
  pull_request: {}
jobs:
  pylint:
    name: Python Code Quality and Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter-env: ["linting", "type_check"]
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v9.0.0
        with:
          python-version: "3.14"
      - name: Install Dependencies
        run: uv sync --group ${{ matrix.linter-env }}
      - name: Run pylint
        if: matrix.linter-env == 'linting'
        run: |
          uv run pylint src/ahbicht
          uv run pylint json_schemas/generate_json_schemas.py
      - name: Run mypy
        if: matrix.linter-env == 'type_check'
        run: |
          uv run mypy --show-error-codes --strict src/ahbicht
          uv run mypy --show-error-codes --strict unittests
          uv run mypy --show-error-codes --strict json_schemas/generate_json_schemas.py
