name: "Linting"

on: [push]
jobs:
  pylint:
    name: Python Code Quality and Lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        linter-env: ["linting", "type_check"]
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.14
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox
      - name: Run ${{ matrix.linter-env}} via Tox
        run: |
          tox -e ${{ matrix.linter-env }}
